export const ReasonCodes = {
  // DATA / QUALITY
  DATA_FAIL_MISSING_FIELDS: "DATA.FAIL.MISSING_FIELDS",
  DATA_FAIL_STALE_FRESHNESS: "DATA.FAIL.STALE_FRESHNESS",
  DATA_FAIL_LOW_COVERAGE: "DATA.FAIL.LOW_COVERAGE",
  DATA_FAIL_INTEGRITY: "DATA.FAIL.INTEGRITY",

  // CONSTRAINTS / CHALLENGE
  CONSTRAINT_HARD_DAILY_LOSS_HIT: "CONSTRAINT.HARD.DAILY_LOSS_HIT",
  CONSTRAINT_HARD_MAX_DD_HIT: "CONSTRAINT.HARD.MAX_DD_HIT",
  CONSTRAINT_HARD_MIN_DAYS_NOT_MET: "CONSTRAINT.HARD.MIN_DAYS_NOT_MET",
  CONSTRAINT_RULES_NEWS_NOT_ALLOWED: "CONSTRAINT.RULES.NEWS_NOT_ALLOWED",
  CONSTRAINT_RULES_WEEKEND_NOT_ALLOWED: "CONSTRAINT.RULES.WEEKEND_NOT_ALLOWED",
  CONSTRAINT_RULES_EA_NOT_ALLOWED: "CONSTRAINT.RULES.EA_NOT_ALLOWED",

  // SESSION / TIME WINDOW
  SESSION_FAIL_OUTSIDE_ALLOWED_BLOCK: "SESSION.FAIL.OUTSIDE_ALLOWED_BLOCK",
  SESSION_FAIL_HARD_CUTOFF_REACHED: "SESSION.FAIL.HARD_CUTOFF_REACHED",
  SESSION_FAIL_EVENT_BUFFER_ACTIVE: "SESSION.FAIL.EVENT_BUFFER_ACTIVE",

  // EXECUTION / COST / MICRO
  EXEC_HALT_SPREAD_P99: "EXEC.HALT.SPREAD_P99",
  EXEC_HALT_SLIPPAGE_P99: "EXEC.HALT.SLIPPAGE_P99",
  EXEC_HALT_ANOMALY_STREAK: "EXEC.HALT.ANOMALY_STREAK",
  COST_FAIL_TAIL_GT_EDGE: "COST.FAIL.TAIL_GT_EDGE",
  COST_RESTRICT_TAIL_NEAR_EDGE: "COST.RESTRICT.TAIL_NEAR_EDGE",
  LIQ_RESTRICT_LOW_LIQUIDITY: "LIQ.RESTRICT.LOW_LIQUIDITY",

  // REGIME / CONFIDENCE
  REGIME_REVIEW_LOW_CONFIDENCE: "REGIME.REVIEW.LOW_CONFIDENCE",
  REGIME_REVIEW_TRANSITION_RISK_HIGH: "REGIME.REVIEW.TRANSITION_RISK_HIGH",
  REGIME_OK_MATCH: "REGIME.OK.MATCH",

  // VENUE / UNIVERSE / SETUP
  VENUE_FAIL_DISABLED_BY_RULES: "VENUE.FAIL.DISABLED_BY_RULES",
  VENUE_FAIL_NO_PRIMARY_UNIVERSE: "VENUE.FAIL.NO_PRIMARY_UNIVERSE",
  UNIVERSE_FAIL_INSTRUMENT_NOT_ALLOWED: "UNIVERSE.FAIL.INSTRUMENT_NOT_ALLOWED",
  SETUP_FAIL_NO_MATCH: "SETUP.FAIL.NO_MATCH",
  SETUP_OK_MATCH: "SETUP.OK.MATCH",

  // RISK BUDGET / PACING
  RISK_FAIL_TRADE_GATE_CLOSED: "RISK.FAIL.TRADE_GATE_CLOSED",
  RISK_RESTRICT_TRADE_GATE_RESTRICTED: "RISK.RESTRICT.TRADE_GATE_RESTRICTED",
  RISK_RESTRICT_PACING_SLOW: "RISK.RESTRICT.PACING_SLOW",
  RISK_OK_ALL_LIMITS_OK: "RISK.OK.ALL_LIMITS_OK",

  // TRADE OK
  TRADE_OK_ALL_GATES: "TRADE.OK.ALL_GATES",
  TRADE_OK_WITH_HAIRCUT: "TRADE.OK.WITH_HAIRCUT",
} as const;

export type ReasonCode = (typeof ReasonCodes)[keyof typeof ReasonCodes];
